# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('uploade_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('cover_photos', models.ImageField(upload_to='cover_photos/%Y/%m')),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('uploade_time', models.DateTimeField()),
                ('photos', models.ImageField(upload_to='photos/%Y/%m')),
            ],
        ),
    ]
