# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170417_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uploade_time',
            new_name='upload_time',
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_date',
            field=models.DateField(default=datetime.date(2017, 4, 17)),
            preserve_default=False,
        ),
    ]
