# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170418_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('upload_time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
