# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_post',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='about_post',
            name='upload_date',
            field=models.DateField(default=datetime.date(2017, 4, 18)),
            preserve_default=False,
        ),
    ]
