# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170418_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=150),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
