# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170417_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='uploade_time',
            new_name='upload_time',
        ),
    ]
