# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170418_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='image_position',
            field=models.CharField(choices=[('blog_img-10', 'blog_img-10')], default=None, max_length=25),
        ),
    ]
