# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_blog_post_img_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='img_pos',
            field=models.CharField(choices=[('blog_img', 'hhh')], default='blog_img', max_length=15),
        ),
    ]
